# Project information

site_name: Amazon Neptune Lab
site_description: 'Amazon Neptune Lab'
#site_author: 'josepenu@amazon.com'
site_url: 'http://neptune.oldschool.cloud'

# Repository
#repo_name: 'name'
repo_url: 'https://github.com/josemp-git/neptune'

google_analytics: ['UA-147241276-2', 'neptune.oldschool.cloud']

# Copyright
copyright: '&copy; 2019 - José Peñúñuri '

extra:
  social:
    - type: 'home'
      link: 'http://neptune.oldschool.cloud'
    - type: 'twitter'
      link: 'https://twitter.com/jose_penunuri'

nav:
    - Inicio: index.md
    - 1. Preparación del ambiente: setup.md
    - 2. Cargar datos en Neptune: cargardatos.md
    - 3. Conectarse a su instancia Neptune: connect.md
    - 4. Consultas con Gremlin: gremlin.md
    - 5. HTTPS REST Endpoint: rest.md
    - 6. Python: python.md
theme:
  name: 'material'
  palette:
    primary: 'Green'
    accent: 'Orange'
  logo:
    icon: 'cloud_done'
markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - markdown.extensions.admonition
  - markdown.extensions.sane_lists
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.def_list
  - markdown.extensions.abbr
  - markdown.extensions.tables
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: True
      separator: "_"
  - pymdownx.extra
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde
  - pyembed.markdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg